// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsj8fVH377t1HlxmFnFLDU2BGhAO9bc5Y',
    appId: '1:330385479279:web:ee122d855f70c0a028df9a',
    messagingSenderId: '330385479279',
    projectId: 'croto-a',
    authDomain: 'croto-a.firebaseapp.com',
    databaseURL: 'https://croto-a-default-rtdb.firebaseio.com',
    storageBucket: 'croto-a.firebasestorage.app',
    measurementId: 'G-P3WDHS0CEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6mV0rNpGZNxEJBR5OnEmDbK8x70eWiyI',
    appId: '1:330385479279:android:31af42f94aaa5f5d28df9a',
    messagingSenderId: '330385479279',
    projectId: 'croto-a',
    databaseURL: 'https://croto-a-default-rtdb.firebaseio.com',
    storageBucket: 'croto-a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0dgJDK1DoUqUzRDhu5OzMDdv7oCr6Q08',
    appId: '1:330385479279:ios:440effe7738edeba28df9a',
    messagingSenderId: '330385479279',
    projectId: 'croto-a',
    databaseURL: 'https://croto-a-default-rtdb.firebaseio.com',
    storageBucket: 'croto-a.firebasestorage.app',
    iosClientId: '330385479279-janem10ltkdoo1p4anlqbbdc4m38chlq.apps.googleusercontent.com',
    iosBundleId: 'com.anandnet.harmonymusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0dgJDK1DoUqUzRDhu5OzMDdv7oCr6Q08',
    appId: '1:330385479279:ios:440effe7738edeba28df9a',
    messagingSenderId: '330385479279',
    projectId: 'croto-a',
    databaseURL: 'https://croto-a-default-rtdb.firebaseio.com',
    storageBucket: 'croto-a.firebasestorage.app',
    iosClientId: '330385479279-janem10ltkdoo1p4anlqbbdc4m38chlq.apps.googleusercontent.com',
    iosBundleId: 'com.anandnet.harmonymusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACenKA1vosi9Xco8Ner-FE3NRyGMt_OPw',
    appId: '1:330385479279:web:74c8a5b35b3e885528df9a',
    messagingSenderId: '330385479279',
    projectId: 'croto-a',
    authDomain: 'croto-a.firebaseapp.com',
    databaseURL: 'https://croto-a-default-rtdb.firebaseio.com',
    storageBucket: 'croto-a.firebasestorage.app',
    measurementId: 'G-55LPFXENNJ',
  );
}
